DROP TABLE  IF EXISTS STOCKS;
CREATE TABLE STOCKS (
    id INT NOT NULL AUTO_INCREMENT,
    symbol VARCHAR(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    Market_Cap VARCHAR(20),
    Country VARCHAR(20),
    IPO_Year VARCHAR(6),
    Sector VARCHAR(25),
    Industry VARCHAR(70),
    PRIMARY KEY(id, symbol),
    UNIQUE KEY (symbol)
);


DROP TABLE IF EXISTS STOCK_DAILY;
CREATE TABLE STOCK_DAILY(
    ID INT NOT NULL AUTO_INCREMENT,
    closing_dt DATE NOT NULL,
    Close varchar(10),
    symbol VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (SYMBOL) REFERENCES STOCKS(symbol)
    );
